### ISSUE TITLE
not getting same performance as in perf_client

### ISSUE THREAD

**Issue by ishantbansal** [NVIDIA/triton-inference-server#1158]
i used perf_client to get max inference count i can get from my model but it is not matching with real results which i am getting with my client . I am using shared memory in both .

TRTIS 20.02 docker & 20.02 client sdk

**Comment by CoderHam** [comment]
What parameters are you using to run perf client?
Is your client code in c++ as well? 
 Please share more details i.e. the number of inferences from both and your client code so I can help you. 
If you're using the same concurrency level and being efficient with your shared memory regions such as create a large one and use sections of it and registering them in advance you should be getting a similar performance.

**Comment by CoderHam** [comment]
I'd advise you to have a look at the perf_client and see what we do to maximize performance for shared memory regions

**Comment by ishantbansal** [comment]
perf_client -m model_name -b 8 --shared-memory cuda --output-shared-memory-size max_output_size
No my code is in python
what do you mean by creating large shared memory and using sections .. have any sample in python ? i will look into perf_client code and see if i can do improvements in python code
i am sending same batch & same concurrency which is one and for shared memory i am creating same amount of it and registering it on initialisation time , then sending continuous inference requests

**Comment by ishantbansal** [comment]
with perf_client inference time is 41ms whereas with python client it is 51 ms

**Comment by CoderHam** [comment]
The difference in performance can be described by a few factors:
1. The performance with the python client will always be slower than the pure C++ client due to the inherent overhead of using python.
2. If you look at the [simple_shm_client.cc](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c++/examples/simple_shm_client.cc) You will see that only one shared memory region is used and registered in advance before the inference. Sections of that shared memory region are used for different inputs. Since we built a wrapper around shared memory (system and cuda) you would not be able to do this using a python client unless you built your own wrapper for the same. 
**PS**: Since you register the region/s in advance this should not be an issue.
3. The python client does some post processioning after it receives the inference response. This includes parsing the data in shared memory into a python (numpy) array.
