### ISSUE TITLE
fp16 c++ support example

### ISSUE THREAD

**Issue by loveppdog** [NVIDIA/triton-inference-server#1361]
fp32 inference is slow for my project.
I want to use fp16 to speed in c++ project.
I cannt find fp16 c++ client example in git and c++ seems not to support fp16 directly.

Where can I get fp16 c++ client exmaple? Thx

**Comment by deadeyegoodwin** [comment]
For the reasons you mention, even if a model uses fp16 internally it will usually still use fp32 for input and output tensors since those have a standard representation. If you use TensorRT to create an fp16 version of your model, or perhaps the ONNX/TensorRT or TF/TensorRT integration describe in the documentation you may get some automatic FP16 optimization of your model without having to use fp16 inputs/outputs.

**Comment by loveppdog** [comment]
We have more models in triton inference server currently and alomost tensorflow_graphdef/tensorflow_savedmodel.  Our client codes just like the simple_client.cc with git. We want to speed up our models inference. I just tried to modify the batchsize(for our unet model speed unuseful and resnet speed OK). How should I try to change our client for speed? (change all  models to TensorRT model and client inference API needs to change too? Or refactor our code like perf_client? perf_client seems to benifit from the sync/batching/schecdule? )
