### ISSUE TITLE
How to use dynamic variable size on multiple dimension?

### ISSUE THREAD

**Issue by yoonjaecho** [NVIDIA/triton-inference-server#1368]
Hi, I'm trying to use trtis for serving instance segmentation now.

But there is a problem with multiple dynamic variable size in detection masks.

Currently, It is built on docker-compose with `nvcr.io/nvidia/tensorrtserver:19.10-py3` and here is my part of `config.pbtxt`
~~~
output [
  {   # This part
    name: "output_detection_masks__0"
    data_type: TYPE_BOOL
    dims: [ -1, -1, -1 ]
  },
  {
    name: "output_detection_classes__1"
    data_type: TYPE_INT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "output_detection_scores__2"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  }
]
~~~

where `output_detection_masks__0` returns ( # detected objects, h, w) shape tensor. (they always have a different shape.)
~~~
tensorrtserver.api.InferenceServerException: [inference:0 21] output 'output_detection_masks__0' for model 'solov2' has shape [427,640] but model configuration specifies shape [-1,-1,-1]

tensorrtserver.api.InferenceServerException: [inference:0 21] unexpected shape for output 'output_detection_masks__0', model configuration shape is [1,-1,-1], inference shape is [100,427,640]
~~~
I've tried several combinations ([1, 1, 1] with reshape([]), [-1, 1, 1] with reshape([]).. ) with `--strict-model-config=false` option, but couldn't figure it out.

Any help?

**Comment by deadeyegoodwin** [comment]
Please include the entire configuration file.
Based on the tensor names it seems like you have a pytorch/torchscript model. As you found --strict-model-config=false can't do much with that framework because the model file doesn't have sufficient meta-data.
Can you try 20.03. We did fix some issues with pytorch in recent releases. Note that you should make sure that the version of pytorch you are using matches the version in Triton. You can find that information in the Triton release notes.

**Comment by yoonjaecho** [comment]
I should have considered the batch dimensions of output tensor.

Solved now.
