### ISSUE TITLE
How to size hpw many  models can be served simultaneously.

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/triton-inference-server#1440]
**Description**
Is there a way to size how models can be served simultaneously in a T4 ?

**Triton Information**
20.3

Are you using the Triton container or did you build it yourself? container

**To Reproduce**
Load a number of models and exercise them simulataneously, should see OOM. 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

Multiple MaskRCNN.

**Expected behavior**
Not OOM.

**Comment by nieksand** [comment]
It depends on the backend you're using.

With Tensorflow it's tricky because TF lazily allocates memory as needed on the first few inferences.  It also comes with its own memory allocator that happily slurps up huge amount of memory, even if not strictly needed by the model.  One thing that can help here is to use Triton's request warmup feature on each model you care about.  You will still OOM, but at least it happens at start-up rather than serving time.

About a year ago, I had particularly bad experiences with Tensorflow + XLA.  The JIT kicks in on each different batch size, is glacially slow, and gives little to negative lift in performance on the architectures I care about.  It's been a year though, so maybe things have improved.

With TensorRT it's pretty straight forward.  You can see and influence the model's activation size at plan generation time.  Things get trickier with dynamic shapes of course.

I don't have enough production experience serving Torch or ONNX models directly to have an opinion on those.

I think the easiest approach is to just measure until it breaks.  Use the model warm-up feature to help force eager memory allocation.

**Comment by deadeyegoodwin** [comment]
@whatdhack when you say OOM are you seeing the server crash, or just some inference requests fail with a reason of OOM?

**Comment by whatdhack** [comment]
It is the later - inference requests fail with a reason of OOM - GPU OOM.

**Comment by whatdhack** [comment]
I think one way out of the GPU OOM issue is  to put some kind of a traffic manager on the web server front end that can meter  http requests.

**Comment by whatdhack** [comment]
Is any of the following avialable in Trinton to configure.

1. tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024) <- this is for TF2 
2. per_process_gpu_memory_fraction = 0.4 <- This is for Y=TF1 

Out of curiosity, how does Triton handle  multiple Tensorflow Saved Models ?  A pointer to any lierature, documentation, code will be appreciate.

**Comment by deadeyegoodwin** [comment]
Triton does not yet support TF2. Triton command-line has a --tf-gpu-memory-fraction flag, see tritonserver --help.

What do you mean by "handle". Triton supports multiple models of all backend types. There are links in the README for "concurrent model support". If you are asking about how it is done in code / practice... the architecture section and some of the presentations listed in the README give some insight.

**Comment by whatdhack** [comment]
Thanks.   Does Trinton run one process for all TF models or each model has its own TF process  ? If 1 process for all models, then setting per_process_gpu_memory_fraction  lower than 1 would actually make the OOM problem worse, right ?.

**Comment by deadeyegoodwin** [comment]
Triton is a single process. If you are only running TF models there is no reason to limit the amount of GPU memory available to TF. As you note, this will only make OOM more likely.

**Comment by whatdhack** [comment]
@deadeyegoodwin, thanks. Is there any documentation on the life-cycle of a TF Saved Model, specially as it pertains to memory usage ?  Looks like there is a monotonic relationship between number of models and  the GPU memory grabbed at the startup. Then there  appears to be more memory grab per model as  they are inferenced.  Is the  memory grabbed at startup roughly proportional to the the weights  of the model ?  What is the extra memory grabbed during inference  used for - data ?

**Comment by deadeyegoodwin** [comment]
You likely need to check the TensorFlow docs to see if they have any discussion of that. Triton relies on the TF code itself to load and manage saved models.
