### ISSUE TITLE
Compilation error using C++ client library on Win10 when doing inference with batch_size > 1 

### ISSUE THREAD

**Issue by francescooliva** [NVIDIA/triton-inference-server#1505]
**Description**
I'm on Win10 OS using Visual Studio 2019 and TRTIS 19.12, I'm using client library trying to run an inference request on a detector stored on the inference server using a batch size > 1, following image_client.cpp as example

**Triton Information**
What version of Triton are you using?
TRTIS  Release 1.9.0, corresponding to NGC container 19.12

Are you using the Triton container or did you build it yourself?
I built it myself the client library following the nvidia documentation guide: https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/client.html#windows-10
The container was pulled from NGC

**To Reproduce**
To get the inference results I'm using the instructions below:
```c++
std::vector<std::map<std::string, std::unique_ptr<nic::InferContext::Result>>>
		results
results.emplace_back();
FAIL_IF_ERR(ctx->Run(&results.back()), "unable to run model");
```		
but then I got this error at compile time:
C2280	'std::pair<const std::string,std::unique_ptr<nvidia::inferenceserver::client::InferContext::Result,std::default_delete<nvidia::inferenceserver::client::InferContext::Result>>>::pair(const std::pair<const std::string,std::unique_ptr<nvidia::inferenceserver::client::InferContext::Result,std::default_delete<nvidia::inferenceserver::client::InferContext::Result>>> &)': attempting to reference a deleted function

No problem and no errors with batch size = 1, i.e. using only the map without the std::vector container
```c++
std::map<std::string, std::unique_ptr<nic::InferContext::Result>>
		result
FAIL_IF_ERR(ctx->Run(&result), "unable to run model");
```		
thanks

**Comment by deadeyegoodwin** [comment]
Seems the compiler on win10 is trying to do a copy of the unique_ptr. You may need to not use a vector that way and instead get the result the same say as you do for the batch size 1 case. You don't need to have a vector there just because you are using a batch size > 1.

You should also look into the experimental V2 clients coming out in the upcoming 20.05 release. There will become the default clients in the near future and should be easier to work with especially when using batch-size > 1.
