### ISSUE TITLE
GRPC Configuration Documentation, Defaults, and Examples

### ISSUE THREAD

**Issue by jeisinge** [NVIDIA/triton-inference-server#1521]
**Is your feature request related to a problem? Please describe.**
We are attempting to optimize Triton as a GRPC server.  We noticed a couple of parameters that we felt should be tuned.  And, without trial and error, we don't know the best approach for optimizing these values.

The values we think might need to be adjusted are:
```shell
--grpc-infer-thread-count	Number of threads handling GRPC inference requests.
--grpc-infer-allocation-pool-size	The maximum number of inference request/response objects that remain allocated for reuse. As long as the number of in-flight requests doesn&apos;t exceed this value there will be no allocation/deallocation of request/response objects.
--pinned-memory-pool-byte-size	The total byte size that can be allocated as pinned system memory. If GPU support is enabled, the server will allocate pinned system memory to accelerate data transfer between host and devices until it exceeds the specified byte size. This option will not affect the allocation conducted by the backend frameworks. Default is 256 MB.
```

`--grpc-infer-thread-count` - is this the concurrent requests that can be processed?  I thought I saw ticket somewhere that mentioned the GRPC interface was non-blocking.  If so, should this be set to the number of CPU cores?

Should `--grpc-infer-allocation-pool-size` and `--pinned-memory-pool-byte-size` be set to the same size?  Or, should `--pinned-memory-pool-byte-size` be larger to enable temp space?

Assuming we have:
 * 1 MB request/response payload
 * 8 CPUs
 * Maximum of 32 requests per second
 * 50 GB of RAM
 * 4 model instances

What is the most efficient Triton configuration for GRPC for this type of model/inference payloads?  Are there other parameters that need to be known?

**Describe the solution you'd like**
It would be great to have a bit more details into these configuration parameters, default values, and a couple of examples on how best to configure them.

**Describe alternatives you've considered**
We have tried the default configuration and `--grpc-infer-thread-count=1024 --grpc-infer-allocation-pool-size=1024 --pinned-memory-pool-byte-size=1073741824.`  Both seem to work.

**Additional context**
We are running in the Triton Docker container.

**Comment by deadeyegoodwin** [comment]
Don't use --grpc-infer-thread-count. It has no impact and is being removed in Triton V2. As you note the grpc endpoint is completely async and can handle any number of concurrent requests.

--grpc-infer-allocation-pool-size can be important if you have large request size (which you do). GRPC uses protobuf which can be inefficient in their create/delete. So this parameter lets you have a pool of request protobuf objects that are reused instead of created/deleted. You likely can see a perf difference if you set it to 1 compared with setting it higher (default is 8). The downside of using a large value is that memory usage will increase since the server will keep the pool of that many request protobufs around even if not in use.

--pinned-memory-pool-byte-size is not related to the grpc endpoint. It is the maximum amount of pinned memory (see CUDA docs) that Triton will use. Pinned memory will accelerate DtoH and HtoD copies. Since your model has large input it can be helpful. You can experiment with it set to 0 and a larger number, like 64MB. I wouldn't set it to 1GB since it does have an overall system impact because it locks virtual pages into memory.

**Comment by jeisinge** [comment]
Thank you!

I have lowered my numbers and I am seeing about the same performance with `perf_client.`  I'll keep them lowered and monitor in production.

**Comment by deadeyegoodwin** [comment]
Great!. Closing, reopen if more feedback.
