### ISSUE TITLE
Changing batch sizes when using cuda shared memory

### ISSUE THREAD

**Issue by maaikez** [NVIDIA/triton-inference-server#1741]
Hello,

I am using the triton inference server in my C++ program. I looked at the examples from version 20.03 (the version I am currently using). But the problem is, the example sets up everything, does 1 run and closes everything. 
I want to use cuda shared memory, but I have some questions about that. 

I want to initialize the shared memory only the first time and then use the allocated memory to copy new data to the shared memory, do inference and copy the output data back to the program. My batch size can be different every time. So when initializing the program, I do a `cudaMalloc` for the maximum input and output size, create a CUDA IPC handle with `cudaSetDevice` and `cudaIpcGetMemHandle` for both input and output shared memory. Then I do a `RegisterCudaSharedMemory` for both input and output shared memory, for the maximum batch size of the model.

Next, I create options, set the batch size to max batch size and I call `AddSharedMemoryResult` for output of the model. Then I set the run options with `SetRunOptions` and finally I call `SetSharedMemory` for the input. Then my initialization is finished.

When I want to run inference, I `cudaMemcpy` the input data to the shared memory and call 'Run'. Well, that works, but I expect the inference server will do inference on the whole input shared memory, because I did not set the batch size, so it does not know there are for example only 2 objects. That's a waste of time (and gpu calculation time). But when I set the batch size, I get `unexpected size <size1> for input x, expecting <size2> for model ...`. 
And when I set the batch size and then call 'SetSharedMemory' again, I get the error that `the input can only be set once with SetSharedMemory` (which makes sense). 

So I actually have two questions:
- Is the initialization how I am supposed to do it or is there a function call I should do every time before calling `Run` on infercontext?
- How do I change the batch size during running and is that necessary?

I hope I am clear enough and the explanation is not too messy. 

Thanks in advance!

**Comment by CoderHam** [comment]
Since you are using the C++ API this is relatively straightforward. If you look at the example cuda shared memory client for 20.03 [here](https://github.com/NVIDIA/triton-inference-server/blob/r20.03/src/clients/c%2B%2B/examples/simple_cuda_shm_client.cc) you will see that a CUDA shared memory region or arbitrary size can be [created](https://github.com/NVIDIA/triton-inference-server/blob/r20.03/src/clients/c%2B%2B/examples/simple_cuda_shm_client.cc#L280-L288) and [registered](https://github.com/NVIDIA/triton-inference-server/blob/r20.03/src/clients/c%2B%2B/examples/simple_cuda_shm_client.cc#L291-L294) with Tritonserver. 

Block of any size you desire (based on batch size in your case) can then be purposed for specific requests using _offset_ and _byte_size_. [Here](https://github.com/NVIDIA/triton-inference-server/blob/r20.03/src/clients/c%2B%2B/examples/simple_cuda_shm_client.cc#L297-L302) you can see that using the offset and byte size the CUDA shared memory region is split into the required size chucks for the inputs. 

You need to call `SetSharedMemory()` (just as you would call `SetRaw()` in the non-shared memory case)  for each input before each inference request (`Run()`). For the outputs you need to call `AddSharedMemoryResult()` (just as you call `AddRawResult()` in the non-shared memory case) before each inference request and read the outputs directly from the respective CUDA shared memory region. 

I hope this answers all your questions. Usually the client examples serve as a good explanation of how to use the C++/Python APIs.

**Comment by maaikez** [comment]
So I need to call 'SetSharedMemory' and 'AddSharedMemoryResult' for every call to the inference server? And after every inference I have to call 'UnregisterSharedMemory'?

Because now I call those functions only once on initialization of the class (and UnregisterSharedMemory on deinitialization). When not using batches, that works fine. Is that how it is supposed to work or do I also have to register and unregister shared memory every time when not using batches?

Anyway, with the batches, I'll try your suggestion!

**Comment by maaikez** [comment]
So I tried some different options now, but was not able to change the batch size.
When calling `SetSharedMemory` more than once, I get the error `The input '<input>' can only be set once with SetSharedMemory`.

So what I do is:
- Initialization (once): `cudaMalloc` for the maximum input and output size, create a CUDA IPC handle with `cudaSetDevice` and `cudaIpcGetMemHandle` and finally `RegisterCudaSharedMemory`. I have a shared memory context (`std::unique_ptr<nvidia::inferenceserver::client::SharedMemoryControlContext>`) as well as a infer contact (`std::unique_ptr<nvidia::inferenceserver::client::InferContext>`) as member variable.

- Run (multiple times): `SetBatchSize` in options, `AddSharedMemoryResult` for the outputs and `SetSharedMemory` for the inputs. `cudaMemcpy` all inputs (the whole batch) to the shared memory. Then call `Run` on the `InferContext` instance. Copy the outputs from the shared memory. Finally `unregisterSharedMemory` for both inputs and outputs. 

- Deinitialization (once): Free cuda memory (`cudaFree`).

Doing it this way, I get the error `The input '<input>' can only be set once with SetSharedMemory`. I requested the shared memory status, but the shared memory region for the input is not in the list after `UnregisterSharedMemory` (as expected).

I also tried to not `UnregisterSharedMemory` every time for the input (but only call `SetBatchSize` and `AddSharedMemoryResult`). But that is also not working, because in that case, when running, inference server expects another input size (the size set for the first inference, of course) and fails.

So what am I doing wrong here?

**Comment by CoderHam** [comment]
You need to **Register** once with the server before sending requests and **Unregister** only after you are done. You also need to call **Reset()** on the respective inputs/outputs before calling **SetSharedMemory**. This allows you to reuse the inputs correctly and remove the metadata from the previous request.

**Comment by deadeyegoodwin** [comment]
But, ideally you should be using r20.06 release and the new V2 client APIs, since those are the forward looking clients and APIs. Everything discussed here with regard to registering and unregistering shared memory still applies with V2, and there are several V2 examples that demonstrate usage.

**Comment by maaikez** [comment]
> You also need to call **Reset()** on the respective inputs/outputs before calling **SetSharedMemory**.

Ok that works. Sorry for not reading the documentation properly. Thanks for your help!

So one last question, when I do not change the batch size (or not even use batches at all in a model), should I `Reset` and `SetSharedMemory` every time as well? 


> But, ideally you should be using r20.06 release and the new V2 client APIs, since those are the forward looking clients and APIs. Everything discussed here with regard to registering and unregistering shared memory still applies with V2, and there are several V2 examples that demonstrate usage.

True. But we have a lot of python scripts using the V1 API and we don't want to change that currently. It's the first thing we will do as soon as the main part of the software is done.
