### ISSUE TITLE
how to stream multisource camera in real-time with trtis

### ISSUE THREAD

**Issue by HoangTienDuc** [NVIDIA/triton-inference-server#1798]
i have several models, for example: detection model, recognition model,...
output of previous model is input of later model. How can i use trtis to stream 10 or more camera in real-time. (not concern in hardware)  @deadeyegoodwin

**Comment by deadeyegoodwin** [comment]
Please take a look at the NVIDIA Deepstream project. Triton is integrated in the latest release. https://developer.nvidia.com/deepstream-sdk

**Comment by HoangTienDuc** [comment]
hi @deadeyegoodwin @tanmayv25  . thank for your reply.
i use multhreading to send multi-source camera to trt server one by one. 
Each thread processes 1 camera corresponding to 1 userdata. Like your [example](https://github.com/NVIDIA/triton-inference-server/blob/r20.02/src/clients/python/examples/simple_sequence_client.py).
Howerver, when i process 2 or 3 camera. i usually got bellow error.
```
 self.batch_size)
  File "/home/ducht/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 1667, in async_run
    inputs, outputs, flags, batch_size, corr_id, priority, timeout_us, contiguous_input)
  File "/home/ducht/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 1293, in _prepare_request
    c_uint64(input_value.size * input_value.itemsize))))
  File "/home/ducht/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 261, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] expecting 1 invocations of SetRaw for input 'input0', one per batch entry
```

**Comment by tanmayv25** [comment]
The inference calls across separate threads are not thread-safe. Looks like `SetRaw` calls are facing a race condition across separate threads. Are you using separate InferContext objects to process streams from different cameras?

**Comment by HoangTienDuc** [comment]
i use same inferContext for different camera

**Comment by HoangTienDuc** [comment]
i think it is similar with your code, you also create 1 infercontext
```
ctx0 = InferContext(FLAGS.url, protocol, model_name, model_version,
                        correlation_id=correlation_id0, verbose=FLAGS.verbose,
                        streaming=True)
```
and use this contex for 2 user (1 and 2). but i don't know what corr_id mean. 
In Python API, there are no parameter like corr_id:
```
async_run(inputs, outputs, batch_size=1, flags=0)
```

In

**Comment by tanmayv25** [comment]
The example indeed uses only one InferContext because here only one thread is issuing the requests. There is only one `async_run` call at a time. What I could get from your case was that there are multiple streams from camera sharing the InferContext object, and might be calling their own `async_run`s without protection. Internally, this call sets the inputs with `SetRaw` command and then issue the final inference. These two steps must be atomic. Because `async_run` is not thread-safe, you might be seeing the above exception when setting input for another request was attempted before the earlier request was issued. 

Look here for the `async_run` documentation: [Link](https://github.com/NVIDIA/triton-inference-server/blob/r20.02/src/clients/python/library/__init__.py#L1586-L1641). 

For sequential (stateful) models with multiple instances, users can specify the `correlation_id` with the request. The server will ensure that request with identical `correlation_id` will go to the same model instance. Look [here ](https://docs.nvidia.com/deeplearning/triton-inference-server/archives/tensorrt_inference_server_1110/tensorrt-inference-server-guide/docs/models_and_schedulers.html#stateful-models)for more details.
