### ISSUE TITLE
Custom backend and generic computer vision algorithms

### ISSUE THREAD

**Issue by francescooliva** [NVIDIA/triton-inference-server#1800]
Hi,
Sorry I have a question about custom backend, it's not clear enough for me from the documentation, could I use it to implement non-dnn related models, for example optical flow? thanks

**Comment by deadeyegoodwin** [comment]
You can implement anything you want in a custom backend... as long as your inputs and outputs can be represented by tensors (and because Triton supports variable length tensors you can always send in/out binary blobs so that should be a limiter).
We are working on a new "triton backend" API that has more features, cleaner API and will have better documentation when it is released. You may want to consider using it if you are starting a new custom backend. See src/backends/backend/tritionbackend.h, and in the examples directory the identity.cc file shows a fully documented example (and repeat.cc shows another example demonstrating how the new backend API allows a "decoupling" of requests and responses which is important for some streaming applications like NLP).
