### ISSUE TITLE
Docker container won't start due to entrypoint.sh error

### ISSUE THREAD

**Issue by jgerardsimcock** [NVIDIA/triton-inference-server#1829]
**Description**
I am attempting to spin up 20.06 version of triton server

`docker run  --rm -p 8005:8000 -p8001:8001 -p8002:8002 -v /var/www/models:/models nvcr.io/nvidia/tritonserver:20.06-py3 --model-repository=/models`

`/opt/tritonserver/nvidia_entrypoint.sh: line 92: exec: --: invalid option`

also getting this error 

`ln: failed to create symbolic link '/opt/tritonserver/lib/libnvidia-ml.so.1': File exists`

**Triton Information**
20.06 

I pulled the container from the repo

**To Reproduce**

pull container and run `docker run --gpus=1 --rm -p 8005:8000 -p8001:8001 -p8002:8002 -v /var/www/models:/models nvcr.io/nvidia/tritonserver:20.06-py3 --model-repository=/models`

I have one tensorflow model in my models directory. That directory structure looks like this:
```model_name/1/model.graphdef```
  

**Expected behavior**

I expected the container to start and run with a healthy status.

**Comment by Tabrizian** [comment]
Remove `/opt/tritonserver/lib/libnvidia-ml.so.1'` symbolic link and it should work.  Make sure to not mount the whole directory inside the container.

**Comment by deadeyegoodwin** [comment]
You shouldn't need to remove anything from the container. You are likely following the documentation and there was a bug in there that left out the  "tritonserver". It is fixed in 20.07 docs. Try:

docker run --rm -p 8005:8000 -p8001:8001 -p8002:8002 -v /var/www/models:/models nvcr.io/nvidia/tritonserver:20.06-py3 **tritonserver** --model-repository=/models
