### ISSUE TITLE
Example how to work with shared memory in multi-threaded application?

### ISSUE THREAD

**Issue by asaff1** [NVIDIA/triton-inference-server#1893]
All the provided shared memory examples looks like this one:
https://github.com/NVIDIA/triton-inference-server/blob/master/src/clients/python/examples/simple_http_shm_client.py
How an application which uses threads should manage the shared memory handles? I assume they are not thread safe?

Second, the parameters `triton_shm_name`, `shm_key` - why both are needed? I assume shm_key is the name for `shm_open`. Why the other parameter?

**Comment by CoderHam** [comment]
When using threads you would need to use mutex and locking to prevent overwriting data in the shared memory region. Two threads can read simultaneously from the same section of a shared memory region but not write simultaneously. In that sense yes it is not thread safe. 

Coming to the need for both `triton_shm_name` and `shm_key`, a shared memory region need not entirely be registered in triton. A section of it can be mmaped instead by using an `offset` and `byte_size`. The triton_shm_name refers to the offset-ted block of memory in shared memory of size `byte_size`.

If you refer to https://github.com/NVIDIA/triton-inference-server/blob/master/docs/protocol/extension_shared_memory.md you will see further explanation of the same.  

When working with threads, I would recommend declaring a single large shared memory region that you then break into smaller blocks. i.e. if a region of size 128MB is created, the first 2MB can be used for Input_0, the next 2MB can be used for output_0. Repeat the same for each thread. Thus if there is 1 input and 1 output with 64 threads that run concurrently and each Input/Output is of size 2MB, a shared memory region of 128MB would fit all i/o. Since each thread would read/write into different parts of the shared memory region you need not use locking in this case.

**Comment by bfreskura** [comment]
@CoderHam 

Could you provide a minimal example of using multiple threads and SHM using the Python client? Such an example would be very useful to have among the other client examples.
