### ISSUE TITLE
How to safely restart/pullout a triton server in prod env?

### ISSUE THREAD

**Issue by onriv** [NVIDIA/triton-inference-server#1927]
When running on prod with quite a lot payload, we need to update a model. For some resource limitation like memoery/gpu memory, we have to pull the serer out and switch model version and restart it.

How can we wait till that all requests in the server have been handled plz? is that any api like shutdown?

**Comment by deadeyegoodwin** [comment]
If you send Triton a sighup it will wait for all inflight inference requests to complete before shutting down. You can see this in the console output. Run perf_client against triton so that there are in-flight inferences and then try to stop triton... you will see it waiting for the inflight inferences to complete. By default triton will wait 30 seconds for inflight infrences to complete before forcefully exiting, but there is a command-line arg to adjust that.
